# tasks file for rstudio
---
- name: install | dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ rstudio_dependencies }}"
  tags:
    - rstudio-install-dependencies

- name: install | additional
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ rstudio_install }}"
  tags:
    - rstudio-install-additional

- name: install | create (download) directory
  file:
    path: "{{ rstudio_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - rstudio-install-download
    - rstudio-install-download-directory

- name: install | download deb
  command: >
    curl -sS https://download1.rstudio.org/rstudio-{{ rstudio_version }}-{{ rstudio_machine_map[ansible_machine] }}.deb
      -o {{ rstudio_downloads_path }}/rstudio-{{ rstudio_version }}-{{ rstudio_machine_map[ansible_machine] }}.deb
  args:
    creates: "{{ rstudio_downloads_path }}/rstudio-{{ rstudio_version }}-{{ rstudio_machine_map[ansible_machine] }}.deb"
  tags:
    - rstudio-install-download
    - rstudio-install-download-deb

- name: install | install deb
  apt:
    deb: "{{ rstudio_downloads_path }}/rstudio-{{ rstudio_version }}-{{ rstudio_machine_map[ansible_machine] }}.deb"
  tags:
    - rstudio-install-install
    - rstudio-install-install-deb
