# tasks file
---
- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ rstudio_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - rstudio-install-dependencies

- name: install | additional
  ansible.builtin.apt:
    name: "{{ rstudio_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - rstudio-install-additional

- name: install | create (download) directory
  ansible.builtin.file:
    path: "{{ rstudio_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - rstudio-install-download
    - rstudio-install-download-directory

- name: install | download deb  # noqa command-instead-of-module
  ansible.builtin.command: >
    curl --silent --show-error --fail --location
    {{ rstudio_download_url }}
    -o {{ rstudio_downloads_path }}/rstudio-{{ rstudio_version }}-{{ rstudio_machine_map[ansible_machine] }}.deb
  args:
    creates: "{{ rstudio_downloads_path }}/rstudio-{{ rstudio_version }}-{{ rstudio_machine_map[ansible_machine] }}.deb"
  tags:
    - rstudio-install-download
    - rstudio-install-download-deb

- name: install | install deb
  ansible.builtin.apt:
    deb: "{{ rstudio_downloads_path }}/rstudio-{{ rstudio_version }}-{{ rstudio_machine_map[ansible_machine] }}.deb"
  tags:
    - rstudio-install-install
    - rstudio-install-install-deb
