# tasks file
---
- name: include variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - rstudio
    - rstudio-include-variables

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - rstudio
    - rstudio-install
